### ISSUE TITLE
Request: Temporary accounts on Testnet

### ISSUE THREAD

**Issue by JerkyTreats** [portto/blocto-sdk#16]
I'm integrating Flow/FCL with Blocto. Testing new user flow is a pain because my email is already tied to a wallet, and blocto too clever to allow `test@example.com`. 

A testnet only feature to have temporary/ephemeral wallets would be appreciated.

**Comment by boczeratul** [comment]
You can use emails like
`hello@gmail.com`
`hello+1@gmail.com`
`hello+2@gmail.com`
and they all go to your same mailbox
