### ISSUE TITLE
Use different session keys for different environments

### ISSUE THREAD

**Issue by boczeratul** [portto/blocto-sdk#25]
### The issue
Currently the login session preservation uses the same key in `LocalStorage`, across different environments (mainnet vs. testnet)
https://github.com/portto/blocto-sdk/blob/30635a0fbad005c36c4d56e9d3fd7582b9f5632f/src/providers/blocto.ts#L18

For developers that are testing the same site domain (i.e. `localhost:3000`) and is switching between networks, the login session may be mixed up and cause troubles

### Possible solution
Use different `LocalStorage` keys across different networks

**Comment by akira02** [comment]
Fixed #154
